In [1]:
import networkx as nx
from networkx.algorithms import bipartite
from sklearn.cluster import KMeans
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import json

from IPython import display

In [2]:
df_treaties = pd.read_csv('data/mytreaties.csv')
df_treaties

           State Affiliation   treaty
0      Argentina     Treaty1  Treaty1
1        Belgium         NaN  Treaty2
2          China     Treaty1  Treaty3
3        Denmark         NaN      NaN
4        Ecuador         NaN      NaN
5        Finland     Treaty1      NaN
6         Guyana         NaN      NaN
7    Netherlands         NaN      NaN
8       Paraguay     Treaty1      NaN
9   South Africa         NaN      NaN
10           USA         NaN      NaN
11      Zimbabwe     Treaty1      NaN
12     Argentina         NaN      NaN
13       Belgium     Treaty2      NaN
14         China         NaN      NaN
15       Denmark     Treaty2      NaN
16       Ecuador         NaN      NaN
17       Finland         NaN      NaN
18        Guyana         NaN      NaN
19   Netherlands     Treaty2      NaN
20      Paraguay         NaN      NaN
21  South Africa         NaN      NaN
22           USA     Treaty2      NaN
23      Zimbabwe     Treaty2      NaN
24     Argentina         NaN      NaN
25       Belgium     Treaty3      NaN
26         China         NaN      NaN
27       Denmark         NaN      NaN
28       Ecuador     Treaty3      NaN
29       Finland         NaN      NaN
30        Guyana     Treaty3      NaN
31   Netherlands         NaN      NaN
32      Paraguay     Treaty3      NaN
33  South Africa     Treaty3      NaN
34           USA         NaN      NaN
35      Zimbabwe     Treaty3      NaN